### ISSUE TITLE
Language Mixture

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/powerbi-docs.de-de#6] opened 2019-07-19 10:31 UTC
The page is supposed to appear in German. Everything is in german, the navigation, the links, even the screenshots. Except the content (the main text) although it sais it could be an automatic translation. But it isn't. It's no translation.
That's not a severe problem for me but it's surprising.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ed468ec7-192b-8ad4-da13-fc3bca5c47b8
* Version Independent ID: a93614a9-2bda-3bb5-782b-ec75cd434105
* Content: [Azure und Power BI - Power BI](https://docs.microsoft.com/de-de/power-bi/service-azure-and-power-bi#feedback)
* Content Source: [powerbi-docs/service-azure-and-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/service-azure-and-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment] 2019-07-19 10:47
Hello, @MartinBubenheimer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-07-19 19:02
Hello @MartinBubenheimer 

Thank you for your feedback.

I cannot reproduce this error. Can you please check if the "Read in english" button is active on your end?
![imagen](https://user-images.githubusercontent.com/26746247/61558798-69216000-aa3e-11e9-8180-4ba382a77fa5.png)

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-07-23 18:33
Hello, @MartinBubenheimer
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-07-26 20:12
Hello, @MartinBubenheimer
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team

**Closed by CeciAc** 2019-07-26 20:12 UTC
Labels: Technical Issue
